#!/bin/bash

echo "=========================="
echo "RIDON - bootanimation"
echo "Membuat bootanimation.zip"
echo "=========================="
echo -n "Masukan resolusi [ENTER]: "
read ukuran	

if [ $(ls | grep $ukuran) > 0 ]
then
	echo -n "Berkas sudah ada [ENTER] "
else
	
	mkdir -p $ukuran/part0
	mkdir -p $ukuran/part1
	echo "$ukuran $ukuran 15" > $ukuran/desc.txt
	echo "p 1 0 part0" >> $ukuran/desc.txt
	echo "p 0 0 part1" >> $ukuran/desc.txt
	
	cd $ukuran/part0
	for ((i=1;i<=99;i++));
	do
	inkscape ../../dasar.svg --export-id-only --export-id=Layer$i --export-png=00$i.png --export-width=$ukuran --export-height=$ukuran
	done
	
	for((a=1;a<=9;a++));
	do
		mv 00$a.png 000$a.png
	done
	
	mv 0099.png ../part1/
	
	cd ..

	
	echo "Membuat berkas bootanimation.zip"
	echo "=========================="
	echo "Mohon tunggu ......"
	zip -r -0 bootanimation.zip part0 part1 desc.txt
	
	echo "Menghapus berkas temporari"
	echo "=========================="
	rm -rf part0/ part1/ desc.txt
	
	echo -n	"Selesai, Terima kasih telah menunggu [ENTER]..."
fi


read end



